spring.application.name=appointmentScheduling

# Database connection
spring.datasource.url=jdbc:postgresql://dpg-d7bh6jhr0fns7399bhog-a.ohio-postgres.render.com:5432/appointmentdb_connection?sslmode=require
spring.datasource.username=appointmentdb_connection_user
spring.datasource.password=JgxQI98rkSZucT10hkgplgC0XhPwJUYF
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Logging SQL (optional, useful for debugging)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
